config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get "sessions/new"
  # get "sessions/create"
  # get "sessions/login"
  # get "sessions/welcome"
  resources :order_products
  resources :product_categories
  resources :products do
    collection do
      get "new_products"
      get "on_sale"
      get "recently_updated"
      get "search"
    end
  end
  resources :orders
  resources :statuses
  resources :customers
  resources :provinces
  resources :categories
  resources :pages, except: [:show]
  resources :cart, only: %i[create destroy]
  get "/pages/:permalink" => "pages#permalink", as: "permalink"

  root "sessions#welcome"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  post "/logout", to: "sessions#destroy"
  get "/welcome", to: "sessions#welcome"

  get "/products_in_cart", to: "cart#index", as: "products_in_cart"
  post "/change_quantity", to: "cart#change_quantity",
                           as: "change_quantity"

  scope "/checkout" do
    post "create",  to: "checkout#create", as: "checkout_create"
    get  "success", to: "checkout#success", as: "checkout_success"
    get  "cancel",  to: "checkout#cancel",  as: "checkout_cancel"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories

  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  attr_accessor :password

  # has_secure_password
  belongs_to :province
  has_many :orders

  validates :username, :first_name, :last_name, :address, :city, :postal_code,
            :telephone, :country, :email, presence: true
  validates :username, uniqueness: true
  validates :password, presence: true, on: :create

  before_validation(on: :create) do
    encrypt_password
  end

  def authenticate(password)
    password_hash == BCrypt::Engine.hash_secret(password, password_salt)
  end

  private

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :status

  has_many :order_products
  has_many :products, through: :order_products

  validates :customer, :status, :total_tax_rate, :total_paid, presence: true
  validates :total_tax_rate, :total_paid, numericality: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, :price, presence: true
  validates :price, :quantity, numericality: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image

  has_many :product_categories, dependent: :delete_all
  has_many :categories, through: :product_categories

  has_many :order_products
  has_many :orders, through: :order_products

  accepts_nested_attributes_for :product_categories, allow_destroy: true

  validates :name, :description, :price, presence: true
  validates :price, numericality: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  # validates :HST, :PST, :GST, numericality: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true

  belongs_to :province
  has_many :orders
  # has_one :province, dependent: :destroy
  # accepts_nested_attributes_for :province

  # def province
  #   super || build_province
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show; end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit; end

  # POST /customers or /customers.json
  def create
    # print customer_params
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        session[:user_id] = @customer.id
        session[:username] = @customer.username
        # redirect_to "/welcome"
        ModelMailer.new_customer_notification(@customer).deliver
        format.html { redirect_to "/welcome", notice: "Customer was successfully created." }
        # format.html { redirect_to @customer, notice: "Customer was successfully created." }
        # format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def customer_params
    params.require(:customer).permit(:username, :password, :first_name, :last_name, :address,
                                     :city, :province_id, :postal_code, :telephone, :country, :email)
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/customers/_form.html.erb
<div class="columns is-centered" >
  <div class="column is-half">
    <div class="card" >
      <div class="card-content ">
        <h1 class="title">Registration</h1>
        <%= form_with(model: customer) do |form| %>
          <% if customer.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

              <ul>
                <% customer.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.label :username %>
            <%= form.text_field :username, class:"input" %>
          </div>

          <div class="field">
            <%= form.label :password %><br />
            <%= form.password_field :password, autocomplete: "new-password" , class:"input" %>
          </div>
          <div class="field">
            <%= form.label :first_name %>
            <%= form.text_field :first_name , class:"input" %>
          </div>

          <div class="field">
            <%= form.label :last_name %>
            <%= form.text_field :last_name, class:"input"  %>
          </div>

          <div class="field">
            <%= form.label :address %>
            <%= form.text_field :address, class:"input"  %>
          </div>

          <div class="field">
            <%= form.label :city %>
            <%= form.text_field :city, class:"input"  %>
          </div>

          <div class="field">
            <%= form.label :province_id, class: ""%>
            <%= form.collection_select( :province_id, return_provinces , :id, :name)%>
          </div>

          <div class="field">
            <%= form.label :postal_code %>
            <%= form.text_field :postal_code , class:"input" %>
          </div>

          <div class="field">
            <%= form.label :telephone %>
            <%= form.text_field :telephone , class:"input" %>
          </div>

          <div class="field">
            <%= form.label :country %>
            <%= form.text_field :country, class:"input"  %>
          </div>

          <div class="field">
            <%= form.label :email %>
            <%= form.text_field :email , class:"input" %>
          </div>

          <div class="actions">
            <%= form.submit%>
          </div>
        <% end %>
      </div>
      <footer class="card-footer">

      </footer>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>City</th>
      <th>Province</th>
      <th>Postal code</th>
      <th>Telephone</th>
      <th>Country</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.username %></td>
        <td><%= customer.password %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.city %></td>
        <td><%= customer.province_id %></td>
        <td><%= customer.postal_code %></td>
        <td><%= customer.telephone %></td>
        <td><%= customer.country %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<%= render 'form', customer: @customer %>

<%= link_to 'Back', '/welcome' %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @customer.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @customer.password %>
</p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Province:</strong>
  <%= @customer.province_id %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @customer.postal_code %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @customer.telephone %>
</p>

<p>
  <strong>Country:</strong>
  <%= @customer.country %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>