config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get "sessions/new"
  # get "sessions/create"
  # get "sessions/login"
  # get "sessions/welcome"
  resources :order_products
  resources :product_categories
  resources :products do
    collection do
      get "new_products"
      get "on_sale"
      get "recently_updated"
      get "search"
    end
  end
  resources :orders
  resources :statuses
  resources :customers
  resources :provinces
  resources :categories
  resources :pages, except: [:show]
  resources :cart, only: %i[create destroy]
  get "/pages/:permalink" => "pages#permalink", as: "permalink"

  root "sessions#welcome"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  post "/logout", to: "sessions#destroy"
  get "/welcome", to: "sessions#welcome"

  get "/products_in_cart", to: "cart#index", as: "products_in_cart"
  post "/change_quantity", to: "cart#change_quantity",
                           as: "change_quantity"

  scope "/checkout" do
    post "create",  to: "checkout#create", as: "checkout_create"
    get  "success", to: "checkout#success", as: "checkout_success"
    get  "cancel",  to: "checkout#cancel",  as: "checkout_cancel"
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories

  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  attr_accessor :password

  # has_secure_password
  belongs_to :province
  has_many :orders

  validates :username, :first_name, :last_name, :address, :city, :postal_code,
            :telephone, :country, :email, presence: true
  validates :username, uniqueness: true
  validates :password, presence: true, on: :create

  before_validation(on: :create) do
    encrypt_password
  end

  def authenticate(password)
    password_hash == BCrypt::Engine.hash_secret(password, password_salt)
  end

  private

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :status

  has_many :order_products
  has_many :products, through: :order_products

  validates :customer, :status, :total_tax_rate, :total_paid, presence: true
  validates :total_tax_rate, :total_paid, numericality: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, :price, presence: true
  validates :price, :quantity, numericality: true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image

  has_many :product_categories, dependent: :delete_all
  has_many :categories, through: :product_categories

  has_many :order_products
  has_many :orders, through: :order_products

  accepts_nested_attributes_for :product_categories, allow_destroy: true

  validates :name, :description, :price, presence: true
  validates :price, numericality: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

  validates :name, presence: true
  # validates :HST, :PST, :GST, numericality: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :orders

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true

  belongs_to :province
  has_many :orders
  # has_one :province, dependent: :destroy
  # accepts_nested_attributes_for :province

  # def province
  #   super || build_province
  # end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_headerOnTop.html.erb
      <div>
        <div class="columns is-multiline m-0">
            <div class="column auto p-0">
               <a class="navbar-item p-0 mt-2" href="/">
                    <img src="/assets/logo.jpg" alt="logo" width="60" height="60" />
                </a>
            </div>
            <div class="column is-two-thirds has-background-white mgt-large mgb-large p-0">
                <%= form_with(url: search_products_path, method: :get, local: true) do |form| %>
                    <div class="field is-horizontal mb-0">
                        <div class="field is-horizontal mb-0">
                            <%= form.label :name, "Search:", class: "tags is-small m-2" %>
                            <%=  form.text_field(:name, class: "input is-small m-2", placeholder: "Search For Products")  %>
                        </div>

                        <%= form.label :category_name, class: "m-2"%>
                            <%= form.collection_select(:category_name, return_categories , :name, :name, {:include_blank => "All"}, {class: "select is-small m-2" })%>

                        <div class="control mb-0">
                            <%= form.submit("Search", class: "button is-primary is-small m-2") %>
                        </div>
                    </div>
                <% end %>
            </div>

            <div class="column auto p-0" style="display:flex;flex-direction: row;">
                <% if logged_in? %>
                    <h2 class=" is-small p-0 mt-2" style="white-space: nowrap; ">Hello, <%= current_user.username %></h2>
                    <div class="is-inline"><%= button_to "Sign Out", '/logout', method: :post, class: "is-inline button is-small m-2" %></div>
                <% else %>
                    <div class="is-inline"><%= button_to "Login", '/login', method: :get, class: "button is-small m-2"  %></div>
                    <div class="is-inline"><%= button_to "Sign Up", '/customers/new', method: :get, class: "button is-primary is-small m-2"  %></div>
                <% end %>
            </div>
        </div>

        <nav class="navbar" role="navigation">
            <div class="navbar-brand">

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <%= link_to "New Products", new_products_products_path, class:"navbar-item" %>
                    <%= link_to "On Sale", on_sale_products_path, class:"navbar-item" %>
                    <%= link_to "Recently Update", recently_updated_products_path, class:"navbar-item" %>
                    <%= link_to "All Products", products_path, class:"navbar-item " %>

                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">Categories</a>

                        <div class="navbar-dropdown">
                            <% return_categories.each do |category| %>
                                <%= link_to category.name, category, class:"navbar-item" %>
                            <% end %>
                        </div>
                    </div>

                    <%= link_to "Orders", orders_path, class:"navbar-item " %>

                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link"> More </a>

                        <div class="navbar-dropdown">
                            <% cms_pages.each do |page| %>
                                <%= link_to page.title, permalink_path(page.permalink), class:"navbar-item" %>
                            <% end %>
                        </div>
                    </div>

                </div>


                <div class="navbar-end" style=" margin-right: 150px;">
                    <div class="navbar-item has-dropdown is-hoverable mr-6">
                        <div class="navbar-link">
                            <%= link_to image_tag("shopping-cart.png",alt:"cart", width:40, height:60), products_in_cart_path, class:"hvr-pulse-grow" %>
                            <% if cart.present? %>
                                <sup style="position:relative;left:-8px;top:-13px;background-color:#920de9;border-radius:7px;color:white;font-weight: bold;margin: 0.2rem;padding: 0.2rem 0.3rem;"><%= cart.size %></sup>
                            <% end %>
                        </div>

                        <div class="navbar-dropdown">
                            <ul>
                                <% if cart.present? %>
                                    <% cart.each do |product| %>
                                        <li class="navbar-item">
                                            <%= product.name %> <%= link_to "Delete" + '➖', cart_path(product), method: :delete, class:"hvr-pulse-grow has-text-danger ml-5" %>
                                        </li>
                                    <% end %>
                                <% end %>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>EcommerceProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://js.stripe.com/v3"></script>
    <%= stylesheet_link_tag "custom_link_style.css" %>
  </head>

  <body>
    <div class="mx-2 mb-6">

        <div class="mb-6">
          <%= render "layouts/headerOnTop" %>
        </div>
        <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
        <% end %>

        <%= yield %>
    </div>

  </body>
</html>